---
title: "Rappoort de Stage - GRAPHES - ODD"
author: "Pape Mamadou BADJI"
date: "`r Sys.Date()`"
output: html_document
---




```{r}
# Installer les packages si nécessaire
#install.packages(c("ggplot2", "showtext"))

# Charger les librairies
library(ggplot2)
library(showtext)

# Ajouter une police propre pour un rendu mémoire
#font_add_google("Roboto", "roboto")
# showtext_auto()

# Données exactes EHCVM
pauvrete <- data.frame(
  annee = c("2011", "2019", "2022"),
  taux = c(46.70, 37.40, 37.50)
)

# Diagramme en barres
ggplot(pauvrete, aes(x = annee, y = taux, fill = annee)) +
  geom_bar(stat = "identity", width = 0.6, show.legend = FALSE) +
  geom_text(aes(label = paste0(taux, "%")), vjust = -0.5, size = 5, family = "roboto") +
  scale_fill_manual(values = c("#0072B2", "#D55E00", "#009E73"))+
  theme_minimal(base_family = "roboto") +
  theme(
    plot.title = element_text(size = 18, face = "bold"),
    plot.subtitle = element_text(size = 14, margin = margin(b = 10)),
    axis.title = element_text(size = 13, face = "bold"),
    axis.text = element_text(size = 12),
    plot.caption = element_text(size = 10, hjust = 0, color = "gray40"),
    panel.grid.minor = element_blank()
  )

```



```{r}

# Charger les librairies
library(ggplot2)
library(showtext)

# Ajouter une police propre pour un rendu mémoire
#font_add_google("Roboto", "roboto")
#showtext_auto()

# Données exactes EHCVM
pauvrete <- data.frame(
  annee = c("2011", "2019", "2022"),
  taux = c(46.70, 37.80, 37.50)
)

# Diagramme en barres épuré
ggplot(pauvrete, aes(x = annee, y = taux, fill = annee)) +
  geom_bar(stat = "identity", width = 0.6, show.legend = FALSE) +
  geom_text(aes(label = paste0(taux, "%")), vjust = -0.2, size = 5, family = "roboto") +
  scale_fill_manual(values = c("#0072B2", "#D55E00", "#009E73")) +
  theme_minimal(base_family = "roboto") +
  theme(
    axis.title = element_blank(),
    axis.text = element_text(size = 10),
    panel.grid.minor = element_blank(),
    panel.grid.major.x = element_blank()
  )

```

